name: '📝 Create/Update Release Draft & Release Bump PR'

on:
  workflow_dispatch:

jobs:
  call:
    permissions:
      contents: write
      pull-requests: write
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@master
    with:
      repository-name: elhlab/jellyfin-plugin-polyfin
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
